# MoralClaims Configuration

# Locale setting (e.g., en_us, ru_ru)
# You can edit the language files in the lang/ folder
locale: en_us

# Telegram Bot Settings
telegram:
  enabled: true
  bot_token: "YOUR_BOT_TOKEN_HERE"
  bot_username: "YourBotUsername"

# Claim Settings
claims:
  max_claims_per_player: 5
  max_claim_area: 2500      # Maximum claim area (blocks)
  min_claim_area: 25        # Minimum claim area (blocks)
  max_claim_width: 100      # Maximum claim width
  max_claim_length: 100     # Maximum claim length

# Selection Tool Settings
selection:
  tool_name_key: "anvil.tool_name"  # Language key for tool name
  show_particles: true
  particle_interval: 20     # Particle display interval (ticks)

# Hologram Settings
holograms:
  enabled: true
  height_offset: 2.0
  duration_seconds: 10
  
# Messages
messages:
  build_denied:
    - "§c{owner} doesn't allow building here!"
    - "§c{owner} says: build somewhere else!"
    - "§cThis is {owner}'s territory, find your own place!"
    - "§c{owner} doesn't approve of your actions here!"
  
  break_denied:
    - "§c{owner} protects these blocks!"
    - "§cDon't break what belongs to {owner}!"
    - "§c{owner} won't let you break this!"
    - "§c{owner}'s territory is protected!"
  
  interact_denied:
    - "§c{owner} doesn't allow interaction here!"
    - "§cThis belongs to {owner}, hands off!"
    - "§c{owner} says: don't touch!"
    - "§c{owner}'s territory, stay away!"

# Notification Settings
notifications:
  server_broadcast: true
  telegram_notifications: true
  log_actions: true
  group_delay_seconds: 3    # Задержка перед отправкой сгруппированных уведомлений

# Border Visualization Settings
border_visualization:
  enabled: true
  duration_seconds: 10      # Длительность показа границ
  particle_interval_ticks: 10  # Интервал между показом частиц (тики)